# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e8e546f83ef1c566573cffb5e927f89e"
name = "mobile-app"
handle = "mobile-app-16"
application_url = "https://adventure-implies-rolls-ice.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testingproductcustomizer.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_discounts,read_draft_orders,read_orders,read_product_listings,read_products,unauthenticated_write_customers,write_checkouts,write_customers,write_discounts,write_draft_orders,write_orders"

[auth]
redirect_urls = [
  "https://adventure-implies-rolls-ice.trycloudflare.com/auth/callback",
  "https://adventure-implies-rolls-ice.trycloudflare.com/auth/shopify/callback",
  "https://adventure-implies-rolls-ice.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
